In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv("Datasets\\temperature\Weather_Jan_to_Mar_2021.csv")
df2 = pd.read_csv("Datasets\\temperature\TS Weather Data April 2021 .csv")
df3 = pd.read_csv("Datasets\\temperature\TS Weather data May 2021.csv")
df4 = pd.read_csv("Datasets\\temperature\TS Weather data June 2021.csv")
df5 = pd.read_csv("Datasets\\temperature\TS Weather data July 2021.csv")
df6 = pd.read_csv("Datasets\\temperature\TS Weather data August 2021.csv")
df7 = pd.read_csv("Datasets\\temperature\TS Weather data September 2021.csv")
df8 = pd.read_csv("Datasets\\temperature\TS Weather data October 2021.csv")
df9 = pd.read_csv("Datasets\\temperature\TS Weather data November 2021.csv")
df10 = pd.read_csv("Datasets\\temperature\TS Weather data December 2021.csv")
df11 = pd.read_csv("Datasets\\temperature\TS Weather data April 2022..csv")
df12 = pd.read_csv("Datasets\\temperature\TS Weather data May 2022_0.csv")
df13 = pd.read_csv("Datasets\\temperature\TS Weather data June 2022_0.csv")
df14 = pd.read_csv("Datasets\\temperature\TS Weather data July 2022_0.csv")

In [3]:
weather = df1.append([df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14])

C:\Users\Prakhar\AppData\Local\Temp\ipykernel_16512\3741273546.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  weather = df1.append([df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14])


In [4]:
weather.drop(["Unnamed: 10","Unnamed: 11","Unnamed: 12","Unnamed: 13","Unnamed: 14"],axis = 1, inplace = True)

In [5]:
weather.head()

District     Mandal       Date  Rain (mm)  Min Temp (°C)  Max Temp (°C)  \
0  Adilabad  Bheempoor  01-Jan-21        0.0           10.1           30.0   
1  Adilabad  Bheempoor  02-Jan-21        0.0           11.7           29.9   
2  Adilabad  Bheempoor  03-Jan-21        0.0           10.4           30.4   
3  Adilabad  Bheempoor  04-Jan-21        0.0           13.1           30.5   
4  Adilabad  Bheempoor  05-Jan-21        0.0           13.4           29.8   

   Min Humidity (%)  Max Humidity (%)  Min Wind Speed (Kmph)  \
0              37.8              95.7                    0.0   
1              40.6              96.6                    0.0   
2              45.8              97.0                    0.0   
3              38.4              96.4                    0.0   
4              50.7              97.0                    0.0   

   Max Wind Speed (Kmph)  
0                    3.1  
1                    2.2  
2                    2.2  
3                    2.0  
4                    2.0

In [6]:
weather.drop("Mandal", axis = 1, inplace = True)

In [49]:
# weather.to_excel("merged.xlsx")

In [7]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297995 entries, 0 to 18413
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   District               297995 non-null  object 
 1   Date                   297995 non-null  object 
 2   Rain (mm)              297995 non-null  float64
 3   Min Temp (°C)          297995 non-null  float64
 4   Max Temp (°C)          297995 non-null  float64
 5   Min Humidity (%)       297995 non-null  float64
 6   Max Humidity (%)       297992 non-null  float64
 7   Min Wind Speed (Kmph)  246792 non-null  float64
 8   Max Wind Speed (Kmph)  246792 non-null  float64
dtypes: float64(7), object(2)
memory usage: 22.7+ MB


In [8]:
districts = weather['District'].unique()
districts.size

36

In [9]:
weather["Date"] = pd.to_datetime(weather['Date'])
weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297995 entries, 0 to 18413
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype         
---  ------                 --------------   -----         
 0   District               297995 non-null  object        
 1   Date                   297995 non-null  datetime64[ns]
 2   Rain (mm)              297995 non-null  float64       
 3   Min Temp (°C)          297995 non-null  float64       
 4   Max Temp (°C)          297995 non-null  float64       
 5   Min Humidity (%)       297995 non-null  float64       
 6   Max Humidity (%)       297992 non-null  float64       
 7   Min Wind Speed (Kmph)  246792 non-null  float64       
 8   Max Wind Speed (Kmph)  246792 non-null  float64       
dtypes: datetime64[ns](1), float64(7), object(1)
memory usage: 22.7+ MB


In [10]:
weather["Month"] = weather["Date"].dt.month
weather["Day"] = weather["Date"].dt.day

In [11]:
weather.describe()

Rain (mm)  Min Temp (°C)  Max Temp (°C)  Min Humidity (%)  \
count  297995.000000  297995.000000  297995.000000     297995.000000   
mean        3.757771      22.692338      34.097261         46.528906   
std        13.222568       3.789614       3.942691         21.912215   
min         0.000000       3.500000      17.300000         -1.000000   
25%         0.000000      20.800000      31.400000         30.400000   
50%         0.000000      23.400000      33.500000         45.300000   
75%         0.300000      25.200000      37.100000         62.800000   
max       391.000000      34.100000      46.000000        100.000000   

       Max Humidity (%)  Min Wind Speed (Kmph)  Max Wind Speed (Kmph)  \
count     297992.000000          246792.000000          246792.000000   
mean          86.312586               0.129949               8.028867   
std           20.142101               0.686120               7.129613   
min           -1.000000               0.000000               0.000000   
25%           80.700000               0.000000               2.800000   
50%           93.500000               0.000000               7.300000   
75%           99.900000               0.000000              11.600000   
max          100.000000              31.300000              69.800000   

               Month            Day  
count  297995.000000  297995.000000  
mean        6.238900      15.499445  
std         3.026573       8.789010  
min         1.000000       1.000000  
25%         4.000000       8.000000  
50%         6.000000      15.000000  
75%         8.000000      23.000000  
max        12.000000      31.000000

In [12]:
weather['District'].value_counts()

Nalgonda                15593
Nizamabad               14587
Rangareddy              13581
Sangareddy              13430
Siddipet                11921
Bhadradri Kothagudem    11569
Suryapet                11569
Kamareddy               11066
Khammam                 10563
Medak                   10412
Nagarkurnool            10060
Nirmal                   9557
Vikarabad                9390
Adilabad                 9054
Jagtial                  9054
Mancherial               9054
Yadadri Bhuvanagiri      8551
Karimnagar               8048
Mahabubabad              8048
Hyderabad                8048
Mahabubnagar             7881
Kumuram Bheem            7545
Medchal-Malkajgiri       7545
Wanaparthy               7042
Peddapalli               7042
Rajanna Sircilla         6539
Jangaon                  6036
Jogulamba Gadwal         6036
Jayashankar              5533
Narayanpet               5533
Warangal Rural           4624
Mulugu                   4527
Warangal Urban           3179
Warangal  

In [13]:
Districts = {districts[i]:i for i in range(0,len(districts)-1)}
print(Districts)

{'Adilabad': 0, 'Kumuram Bheem': 1, 'Mancherial': 2, 'Nirmal': 3, 'Nizamabad': 4, 'Jagtial': 5, 'Peddapalli': 6, 'Jayashankar': 7, 'Bhadradri Kothagudem': 8, 'Mahabubabad': 9, 'Warangal Rural': 10, 'Warangal Urban': 11, 'Karimnagar': 12, 'Rajanna Sircilla': 13, 'Kamareddy': 14, 'Sangareddy': 15, 'Medak': 16, 'Siddipet': 17, 'Jangaon': 18, 'Yadadri Bhuvanagiri': 19, 'Medchal-Malkajgiri': 20, 'Hyderabad': 21, 'Rangareddy': 22, 'Vikarabad': 23, 'Mahabubnagar': 24, 'Jogulamba Gadwal': 25, 'Wanaparthy': 26, 'Nagarkurnool': 27, 'Nalgonda': 28, 'Suryapet': 29, 'Khammam': 30, 'Mulugu': 31, 'Narayanpet': 32, 'Hanumakkonda': 33, 'Warangal': 34}


In [14]:
weather['District'] = weather['District'].map(Districts)

In [15]:
#Handling missing values
weather.isnull().sum()

District                  1288
Date                         0
Rain (mm)                    0
Min Temp (°C)                0
Max Temp (°C)                0
Min Humidity (%)             0
Max Humidity (%)             3
Min Wind Speed (Kmph)    51203
Max Wind Speed (Kmph)    51203
Month                        0
Day                          0
dtype: int64

In [16]:
weather.drop(['Min Wind Speed (Kmph)','Max Wind Speed (Kmph)'],axis = 1, inplace = True)

In [17]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy = 'median')
weather['Max Humidity (%)'] = imp.fit_transform(weather['Max Humidity (%)'].to_numpy().reshape(-1,1))
# weather['Min Wind Speed (Kmph)'] = imp.fit_transform(weather['Min Wind Speed (Kmph)'].to_numpy().reshape(-1,1))
# weather['Max Wind Speed (Kmph)'] = imp.fit_transform(weather['Max Wind Speed (Kmph)'].to_numpy().reshape(-1,1))

In [18]:
weather['District'] = imp.fit_transform(weather['District'].to_numpy().reshape(-1,1))

In [19]:
weather.isnull().sum()

District            0
Date                0
Rain (mm)           0
Min Temp (°C)       0
Max Temp (°C)       0
Min Humidity (%)    0
Max Humidity (%)    0
Month               0
Day                 0
dtype: int64

In [20]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
weather[['Rain (mm)','Min Temp (°C)','Max Temp (°C)','Min Humidity (%)','Max Humidity (%)','Month','Day']] = scaler.fit_transform(weather[['Rain (mm)','Min Temp (°C)','Max Temp (°C)','Min Humidity (%)','Max Humidity (%)','Month','Day']])

In [21]:
weather.head()

District       Date  Rain (mm)  Min Temp (°C)  Max Temp (°C)  \
0       0.0 2021-01-01        0.0       0.093811       0.278647   
1       0.0 2021-01-02        0.0       0.106736       0.272769   
2       0.0 2021-01-03        0.0       0.092839       0.271375   
3       0.0 2021-01-04        0.0       0.120156       0.279753   
4       0.0 2021-01-05        0.0       0.117197       0.260632   

   Min Humidity (%)  Max Humidity (%)     Month       Day  
0          0.351095          0.888884  0.009288  0.009288  
1          0.370382          0.881253  0.009123  0.018245  
2          0.408848          0.865900  0.008927  0.026780  
3          0.352214          0.884203  0.009172  0.036689  
4          0.443424          0.848365  0.008746  0.043730

In [22]:
corr_matrix = weather.corr()
corr_matrix

C:\Users\Prakhar\AppData\Local\Temp\ipykernel_16512\3248174202.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = weather.corr()


District  Rain (mm)  Min Temp (°C)  Max Temp (°C)  \
District          1.000000  -0.060772      -0.015235      -0.031203   
Rain (mm)        -0.060772   1.000000      -0.192945      -0.266551   
Min Temp (°C)    -0.015235  -0.192945       1.000000       0.919963   
Max Temp (°C)    -0.031203  -0.266551       0.919963       1.000000   
Min Humidity (%) -0.009385   0.228855      -0.593527      -0.815500   
Max Humidity (%)  0.046264  -0.114786      -0.774474      -0.666611   
Month             0.022376  -0.055925       0.218814       0.146492   
Day              -0.006635  -0.108499       0.163606       0.175888   

                  Min Humidity (%)  Max Humidity (%)     Month       Day  
District                 -0.009385          0.046264  0.022376 -0.006635  
Rain (mm)                 0.228855         -0.114786 -0.055925 -0.108499  
Min Temp (°C)            -0.593527         -0.774474  0.218814  0.163606  
Max Temp (°C)            -0.815500         -0.666611  0.146492  0.175888  
Min Humidity (%)          1.000000          0.280759  0.043176 -0.188030  
Max Humidity (%)          0.280759          1.000000 -0.370893 -0.144336  
Month                     0.043176         -0.370893  1.000000 -0.031136  
Day                      -0.188030         -0.144336 -0.031136  1.000000

In [23]:
X = weather.drop(["Date","Max Temp (°C)"],axis = 1)
y = weather["Max Temp (°C)"]

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.svm import LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

In [25]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [33]:
model_name = []
accuracy = []
model_1 = Lasso()
kf = KFold(5)
scores = cross_val_score(model_1,X,y,cv = kf)
print(scores)
print(np.mean(scores))
model_name.append('Lasso')
accuracy.append(np.mean(scores)*100)

[-2.87729740e-02 -3.89838153e-01 -7.28293140e+00 -3.52965810e-01
 -6.99478495e-03]
-1.612300625439358


In [35]:
model_2 = LinearRegression()
scores = cross_val_score(model_2,X,y, cv = kf)
print(scores)
print(np.mean(scores))
model_name.append('Linear Regression')
accuracy.append(np.mean(scores)*100)

[0.78779657 0.82548867 0.8225026  0.88699224 0.95781532]
0.8561190791511724


In [36]:
model_3 = LinearSVR()
scores = cross_val_score(model_3,X,y, cv = kf)
print(scores)
print(np.mean(scores))
model_name.append('Linear SVR')
accuracy.append(np.mean(scores)*100)

c:\Users\Prakhar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\Prakhar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\Prakhar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\Prakhar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


[ 0.76532328  0.77399756 -1.41819717  0.85178779  0.95535083]
0.3856524565817764


c:\Users\Prakhar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [37]:
model_4 = KNeighborsRegressor()
scores = cross_val_score(model_4,X,y, cv = kf)
print(scores)
print(np.mean(scores))
model_name.append('K Neighbors')
accuracy.append(np.mean(scores)*100)

[0.83436927 0.76085369 0.83488121 0.89374697 0.94928699]
0.854627625471832


In [38]:
model_5 = DecisionTreeRegressor()
scores = cross_val_score(model_5,X,y, cv = kf)
print(scores)
print(np.mean(scores))
model_name.append('Decision Tree Regressor')
accuracy.append(np.mean(scores)*100)

[0.86077239 0.91939647 0.86019598 0.78087514 0.95380101]
0.8750081968110818


In [40]:
model_6 = RandomForestRegressor(n_estimators=10)
scores = cross_val_score(model_6,X,y, cv = kf)
print(scores)
print(np.mean(scores))
model_name.append('Random Forest Regressor')
accuracy.append(np.mean(scores)*100)

[0.88739351 0.94311376 0.92546263 0.80603792 0.9628092 ]
0.9049634034417562


In [42]:
model_list = {'Model Name': model_name,'Accuracy':accuracy}
result = pd.DataFrame(model_list)
result.drop([1],axis = 0, inplace = True)
result

Model Name    Accuracy
0                    Lasso -161.230063
2        Linear Regression   85.611908
3               Linear SVR   38.565246
4              K Neighbors   85.462763
5  Decision Tree Regressor   87.500820
6  Random Forest Regressor   90.496340

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 40)

In [46]:
model_6.fit(X_train,y_train)
y_pred = model_6.predict(X_test)
print(model_6.score(X_test,y_test))

0.9958498326390156


In [48]:
import pickle
file = open('model.pkl','wb')
pickle.dump(model_6,file)